openapi: 3.0.3
info:
  title: PatchProof Authentication API
  description: |
    Production-hardened authentication and chain of custody API for SmartLedger PatchProof™. Includes secure claim, transfer, and on-chain anchoring flows.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /verify-request:
    post:
      summary: Request verification code (email or phone)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                phone:
                  type: string
              example: { "email": "user@example.com" }
      responses:
        '200':
          description: Code sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        '400':
          $ref: '#/components/responses/Error'
  /verify-submit:
    post:
      summary: Submit verification code and receive JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                phone:
                  type: string
                code:
                  type: string
              example: { "email": "user@example.com", "code": "123456" }
      responses:
        '200':
          description: JWT issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiresIn:
                    type: integer
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
  /authRecord:
    post:
      summary: Submit an authentication claim (requires JWT)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRecord'
      responses:
        '200':
          description: Record created and signed
          content:
            application/json:
              schema:
                type: object
                properties:
                  txid:
                    type: string
                  signature:
                    type: string
                  pubKey:
                    type: string
                  broadcast:
                    type: object
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
    get:
      summary: Get all authentication records (not implemented)
      responses:
        '501':
          $ref: '#/components/responses/Error'
  /authRecord/{txid}:
    get:
      summary: Get a specific authentication record
      parameters:
        - name: txid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Record found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthRecord'
        '404':
          $ref: '#/components/responses/Error'
  /transfer/request:
    post:
      summary: Initiate transfer (current holder)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                txid:
                  type: string
                newHolder:
                  type: string
      responses:
        '200':
          description: Transfer request created
          content:
            application/json:
              schema:
                type: object
                properties:
                  transferRequest:
                    type: object
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
  /transfer/accept:
    post:
      summary: Accept transfer (new holder)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                txid:
                  type: string
                transferRequest:
                  type: object
      responses:
        '200':
          description: Transfer complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  txid:
                    type: string
                  newHolder:
                    type: string
                  toSig:
                    type: string
                  broadcast:
                    type: object
                  record:
                    $ref: '#/components/schemas/AuthRecord'
        '401':
          $ref: '#/components/responses/Error'
        '400':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
  /verify/{txid}:
    get:
      summary: Verify a record's hash and signature
      parameters:
        - name: txid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  txid:
                    type: string
                  validHash:
                    type: boolean
                  validSig:
                    type: boolean
        '404':
          $ref: '#/components/responses/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
                  requestId:
                    type: string
                  details:
                    type: array
                    items:
                      type: string
  schemas:
    AuthRecord:
      type: object
      properties:
        type:
          type: string
          example: AUTHENTICATION_RECORD
        item:
          type: object
          properties:
            serial_number:
              type: string
            patch_type:
              type: string
            material:
              type: string
            rfid_tag_id:
              type: string
            date_embedded:
              type: string
              format: date-time
        owner:
          type: object
          properties:
            claimed:
              type: boolean
            current_holder:
              type: string
            last_verified:
              type: string
              format: date-time
            history:
              type: array
              items:
                type: object
                properties:
                  from:
                    type: string
                  to:
                    type: string
                  fromSig:
                    type: string
                  toSig:
                    type: string
                  intentHash:
                    type: string
                  acceptanceHash:
                    type: string
                  requestedAt:
                    type: string
                  acceptedAt:
                    type: string
        metadata:
          type: object
          properties:
            image:
              type: string
              format: uri
            patch_location:
              type: string
            notes:
              type: string
        auth:
          type: object
          properties:
            blockchain:
              type: string
            txid:
              type: string
            sha256_hash:
              type: string
            signature:
              type: string
            pubKey:
              type: string
