openapi: 3.0.3
info:
  title: PatchProof API
  version: 1.0.0
  description: API for PatchProof authentication and patch management
servers:
  - url: http://localhost:3001
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /ready:
    get:
      summary: Readiness check
      responses:
        '200':
          description: Ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  database:
                    type: string
        '503':
          description: Not ready
  /v1/admin/utxo-health:
    get:
      summary: UTXO pool health
      description: Returns counts and total satoshis for UTXOs by status.
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Health summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: object
                    properties:
                      count:
                        type: integer
                      totalSatoshis:
                        type: integer
                  locked:
                    type: object
                    properties:
                      count:
                        type: integer
                      totalSatoshis:
                        type: integer
                  spent:
                    type: object
                    properties:
                      count:
                        type: integer
                      totalSatoshis:
                        type: integer
  /v1/admin/batch-anchor:
    post:
      summary: Batch anchor unanchored records
      description: Computes a Merkle root from unanchored records and anchors it on-chain, updating each record with a Merkle proof and anchor txid.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 1000
          required: false
          description: Maximum number of records to process (default 100, max 1000)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: integer
                  minimum: 1
                  maximum: 1000
      responses:
        '200':
          description: Anchoring result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  txid:
                    type: string
                  processed:
                    type: integer
                  updated:
                    type: integer
                  message:
                    type: string
        '500':
          description: Broadcast failure or server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
  /v1/auth/request-verification:
    post:
      summary: Request verification code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
              required:
                - identifier
      responses:
        '200':
          description: Verification initiated
  /v1/auth/submit-verification:
    post:
      summary: Submit verification code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                code:
                  type: string
              required:
                - identifier
                - code
      responses:
        '200':
          description: Verified
  /v1/patches:
    post:
      summary: Register a patch
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    uid_tag_id:
                      type: string
                  required:
                    - uid_tag_id
                metadata:
                  type: object
                paymentAddress:
                  type: string
                auth:
                  type: object
                  properties:
                    owner:
                      type: string
      responses:
        '200':
          description: Registered
  /v1/patches/verify/{uid_tag_id}:
    get:
      summary: Verify a patch
      parameters:
        - in: path
          name: uid_tag_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Verification result
  /v1/patches/{txid}/transfer-ownership:
    post:
      summary: Transfer patch ownership
      security:
        - ApiKeyAuth: []
          bearerAuth: []
      parameters:
        - in: path
          name: txid
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newOwnerAddress:
                  type: string
                currentOwnerSignature:
                  type: string
                currentOwnerPubKey:
                  type: string
              required:
                - newOwnerAddress
                - currentOwnerSignature
                - currentOwnerPubKey
      responses:
        '200':
          description: Ownership transferred
  /v1/patches/{uid_tag_id}/unlock-content:
    post:
      summary: Unlock content for a patch
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: uid_tag_id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        '200':
          description: Content unlocked

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
